trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: irwiss/phpbb
  imageTag: '$(Build.SourceBranchName)-$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName):$(imageTag) -t $(imageName):latest .
  displayName: 'docker build'
- script: docker login -u $(dockeruser) -p $(dockerpass)
  displayName: 'docker login'
- script: docker push $(imageName):$(imageTag)
  displayName: 'docker push tagged'
- script: docker push $(imageName):latest
  displayName: 'docker push latest'
